### PR TITLE
sindy model features

### PR DESCRIPTION
**Pull request by TarenGorman**

### CODE REVIEW

**Comment by Ohjeah** [comment]
Can you vectorize the main for-loop in _derivative?

**Comment by TarenGorman** [comment]
Do you think it best to leave it as two params, dt and timestamps? 

Or.. should it just be the dt param.. and if dt is given as a list/np.array _derivative follows the timestamps logic?

**Comment by Ohjeah** [comment]
You could write a check to make sure that it is either dt or timestamps. Or just default to timestamps if they are provided.

**Comment by Ohjeah** [comment]
Your test fails. Could you please check that?

**Comment by TarenGorman** [comment]
Should be passing now, syntax issue.

**Comment by Ohjeah** [comment]
Sweet.

**Pull request merged**
